use_frameworks!

platform :ios, '15.0'

target 'Rudder-Singular_Example' do
  pod 'Rudder-Singular', :path => '../'

  target 'Rudder-Singular_Tests' do
    inherit! :search_paths

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
